meta_poi_name: "Nom du Poi"
meta_title: "Nom du Poi - Tagline du Product"
meta_description: "Description percutante"
meta_keywords: "Compostelle, St-Jacques-de-Compostelle, Santiago"
meta_image: "logo.png"
twitter_account: "@gr65fr"
